# The Docker image that will be used to build your app
image: alpine

pages:
  script:
      - apk update && apk add doxygen #graphviz ttf-freefont
      - doxygen doc/Doxyfile
      - mv doc/doxygen/html/ public/

  environment: production
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

